Makety/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maket/', include('maket.urls')),
    path('dicts/', include('dictionarys.urls')),
    path('patterns/', include('patterns.urls')),
    path('errors/', include('errors.urls')),
    path('films/', include('films.urls')),
    path('maket_layout/', include('maket_layout.urls')),
    path('addfiles/', include('addfiles.urls')),
    path('orders/', include('orders.urls')),
    path('file_manage/', include('file_manage.urls')),
    path('salesreport/', include('salesreport.urls')),

]

dictionarys/urls.py
from django.urls import path
from . import views

app_name = 'dictionarys'

urlpatterns = [
    path('goods', views.goods, name='goods'),
    path('add_detail', views.add_detail, name='add_detail'),

    path('customers', views.customers, name='customers'),
    path('update_cst', views.update_cst, name='update_cst'),

    path('customer_groups', views.customer_groups, name='customer_groups'),
    path('update_cst_group', views.update_cst_group, name='update_cst_group'),

    path('colors', views.colors, name='colors'),
    path('add_clr', views.add_clr, name='add_clr'),

    path('print_group', views.print_group, name='print_group'),
    path('update_pg', views.update_pg, name='update_pg'),

    path('print_position', views.print_position, name='print_position'),
    path('update_prt_pos/<int:id>', views.update_prt_pos, name='update_prt_pos'),
    path('add_prt_pos', views.add_prt_pos, name='add_prt_pos'),
    path('delete_print_position/<int:id>', views.delete_print_position, name='delete_print_positon'),

    path('matrix', views.good_groups, name='good_groups'),
    path('update_matrix_type/<int:id>', views.update_matrix_type, name='update_matrix_type'),
    path('add_matrix_type', views.add_matrix_type, name='add_matrix_type'),
    path('delete_matrix_type/<int:id>', views.delete_matrix_type, name='delete_matrix_type'),

    path('other', views.other, name='other'),

    path('update_clr_sch/<int:id>', views.update_clr_sch, name='update_clr_sch'),
    path('add_clr_sch', views.add_clr_sch, name='add_clr_sch'),

    path('update_prt_typ/<int:id>', views.update_prt_typ, name='update_prt_typ'),
    path('add_prt_typ', views.add_prt_typ, name='add_prt_typ'),

    path('update_prt_plc/<int:id>', views.update_prt_plc, name='update_prt_plc'),
    path('add_prt_plc', views.add_prt_plc, name='add_prt_plc'),
    path('delete_print_place/<int:id>', views.delete_print_place, name='delete_print_place'),

    path('update_crm_type/<int:id>', views.update_crm_type, name='update_crm_type'),
    path('add_crm_type', views.add_crm_type, name='add_crm_type'),
    path('delete_crm_type/<int:id>', views.delete_crm_type, name='delete_crm_type'),

    path('update_cst_type/<int:id>', views.update_cst_type, name='update_cst_type'),
    path('add_cst_type', views.add_cst_type, name='add_cst_type'),
    path('delete_cst_type/<int:id>', views.delete_cst_type, name='delete_cst_type'),

    path('scale', views.scale, name='scale'),

]

errors/urls.py
from django.urls import path
from . import views

app_name = 'errors'

urlpatterns = [
    path('lost_imports/<int:id>', views.lost_imports, name='lost_imports'),
    path('lost_hex', views.lost_hex, name='lost_hex'),
    path('changed_customers/<int:id>', views.changed_customers, name='changed_customers'),
    path('order_edit/<int:id>', views.order_edit, name='order_edit'),
    path('order_save', views.order_save, name='order_save'),
    path('print_place_connect', views.print_place_connect, name='print_place_connect'),
    path('print_position_fix', views.print_position_fix, name='print_position_fix'),
    path('hex_repairs', views.hex_repairs, name='hex_repairs'),
    path('print_position_repairs', views.print_position_repairs, name='print_position_repairs'),
    path('customer_repairs', views.customer_repairs, name='customer_repairs'),
    path('color_place_repairs', views.color_place_repairs, name='color_place_repairs'),
    path('deleted_repairs', views.deleted_repairs, name='deleted_repairs'),
    path('import_repairs', views.import_repairs, name='import_repairs'),

    path('other', views.other, name='other'),
    path('other/delete_film', views.delete_film, name='delete_film'),

    path('badge_file_count', views.badge_file_count, name='badge_file_count'),


]

films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.films, name='films'),
    path('upload_film', views.upload_film, name='upload_film'),
    path('download_film/<int:id>', views.download_film, name='download_film'),
    path('vieworder/<int:id>', views.vieworder, name='vieworder'),
    path('update_to_film/<str:data_to_film>', views.update_to_film, name='update_to_film'),

]

maket/urls.py
from django.urls import path
from . import views

app_name = 'maket'

urlpatterns = [
    path('maket_base', views.maket_base, name='maket_base'),
    path('maket/maket', views.maket, name='maket'),

    path('maket_status/<int:id>/<str:status>/<str:source>', views.maket_status, name='maket_status'),
    path('save_to_film/<int:id>/<int:film>', views.save_to_film, name='save_to_film'),
    path('upload_maket/<str:look_up>', views.upload_maket, name='maket_order'),
    path('download_maket/<int:id>', views.download_maket, name='download_maket'),
    path('look_up/<str:navi>', views.look_up, name='look_up'),
    path('delete_maket', views.delete_maket, name='delete_maket'),
    path('maket_check_status/<int:id>', views.maket_check_status, name='maket_check_status'),
    path('look_up_not_finished/<str:navi>', views.look_up_not_finished, name='look_up_not_finished'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id_str>', views.reload, name='reload'),
    path('orders/import_order', views.import_order, name='import_order'),
    path('orders/delete_order', views.delete_order, name='delete_order'),
    path('orders/upload_order', views.upload_order, name='upload_order'),
    path('download_order/<int:id>', views.download_order, name='download_order'),
    path('order_edit/<int:id>', views.order_edit, name='order_edit'),
    path('orders/order_save', views.order_save, name='order_save'),
    path('orders/order_errors', views.order_errors, name='order_errors'),
]

patterns/urls.py
from django.urls import path
from . import views

app_name = 'patterns'

urlpatterns = [
    path('', views.patterns, name='patterns'),
    path('upload_pattern', views.upload_pattern, name='upload_pattern'),
    path('download_pattern/<int:id>', views.download_pattern, name='download_pattern'),
]

maket/models/customer_group_models.py
from django.db import models
import datetime


class Customer_types(models.Model):
    type_name = models.CharField(max_length=30)
    group_discount = models.FloatField(default=0)
    code = models.CharField(max_length=2, default='')

    def __repr__(self):
        return self.type_name

    def __str__(self):
        return str(self.type_name)


class Customer_groups(models.Model):
    group_name = models.CharField(max_length=255, unique=True)
    group_type = models.ForeignKey(Customer_types, models.SET_NULL, null=True)
    phone = models.CharField(max_length=255, default='')
    mail = models.CharField(max_length=255, default='')
    date_first = models.DateField(default=datetime.date(2000, 1, 1))
    date_last = models.DateField(default=datetime.date(2000, 1, 1))
    active = models.BooleanField(default=True)


    def __repr__(self):
        return self.group_name

    def __str__(self):
        return str(self.group_name)

maket/forms.py
from django import forms


class FileForm(forms.Form):
    file_name = forms.CharField(label='File name', max_length=100)
    file_body = forms.FileField(label='File body')

maket/views.py
import datetime
import os

from django.db.models import Q, F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import FileResponse, Http404
from Makety.service import *

from .models import Print_place, Print_position, Item_color, Order_imports, Item_imports, \
    Print_imports, Detail_set, Customer, Makety, Films, Itemgroup_in_Maket, Print_group, \
    Print_in_Maket, Print_color, Additional_Files, Customer_types, Customer_groups
from django.views.decorators.csrf import csrf_exempt


def main_maket(request):
    template = loader.get_template('maket/main.html')
    context = {}
    return HttpResponse(template.render({}, request, context))


def maket_base(request):
    navi = 'maket_base'
    maket = Makety.objects.all().order_by('-order_date', 'maket_id').filter(order__isnull=False)
    item_group = Itemgroup_in_Maket.objects.all().order_by('item')
    f_group = {}
    for i in item_group:
        if i.maket not in f_group:
            f_group[i.maket] = []
        if i.checked:
            ig_q = 0
            ig_p = 0
            ig_pp = 0
            try:
                itms = Item_imports.objects.filter(Q(order=i.maket.order) & Q(item__print_group=i.item.item.print_group) \
                                                   & Q(print_name=i.print_name))
                for it in itms:
                    ig_q = ig_q + it.quantity
                    ig_p = ig_p + it.quantity * it.item_price
                    ig_pp = ig_pp + it.quantity * it.print_price
                f_group[i.maket].append([i, ig_q, ig_p, ig_pp])
            except:
                pass
    f_maket = {}
    for m in maket:
        if m.order not in f_maket:
            f_maket[m.order] = {}
        f_maket[m.order].update({m: f_group.get(m)})

    films = Films.objects.filter(status=False).order_by('-date', 'film_id')
    current_date = datetime.date.today()
    try:
        last_film = films.first().film_id + 1
    except:
        last_film = 1

    f_maket2 = list(f_maket.items())
    paginator = Paginator(f_maket2, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    f_maket = dict(page_obj.object_list)

#   date_range = []
#    for i in range(page_obj.paginator.num_pages):
#        page_obj2 = paginator.get_page(i + 1)
#        date_tmp = page_obj2.object_list[-1][0].order_date.strftime('%d.%m.%Y') + ' - ' + \
#                   page_obj2.object_list[0][0].order_date.strftime('%d.%m.%Y')
#        date_range.append([i + 1, date_tmp])

    context = {'navi': navi, 'active5': 'active', 'page_obj': page_obj, 'films': films,
               'current_date': current_date, 'last_film': last_film, 'look_up': False, 'f_maket': f_maket}
    context.update(count_errors())
    return render(request, 'maket/maket_base.html', context)


def maket(request):
    navi = 'maket'
    context = {'navi': navi}
    context.update(count_errors())
    return render(request, 'maket/index.html', context)


def product_range(ord_imp):
    return product_range


def maket_status(request, id, status, source):
    order = Order_imports.objects.get(id=id)
    order.maket_status = status
    order.save()
    if source == 'order':
        return HttpResponseRedirect(reverse('maket:index'))
    if source == 'maket':
        return HttpResponseRedirect(reverse('maket:maket_base'))


@csrf_exempt
def save_to_film(request, id, film):
    item_group = Itemgroup_in_Maket.objects.get(id=id)
    try:
        film = Films.objects.get(id=film)
    except:
        try:
            flm = Films.objects.all().order_by('-date', '-film_id').first().film_id
            flm = flm + 1
        except:
            flm = 1
        film = Films(date=datetime.date.today(), film_id=flm)
        film.save()
    item_group.film = film
    item_group.save()
    return HttpResponse()


def upload_maket(request, look_up):
    id = request.POST['upload_id']
    maket = Makety.objects.get(id=id)
    order = maket.order
    try:
        file = request.FILES['ChoseMaket']
        try:
            maket.maket_file.delete()
        except:
            order.number_makets += 1
        maket.maket_file.save(file.name, file)
        maket.uploaded = True
        maket.save()
        order.maket_status = 'R'
        order.save()
    except:
        pass
    if look_up == 'True':
        return HttpResponseRedirect(reverse('maket:look_up_not_finished', kwargs={'navi': 'maket_base'}))
    else:
        return HttpResponseRedirect(reverse('maket:maket_base'))


def download_maket(request, id):
    maket = Makety.objects.get(id=id)
    try:
        return FileResponse(open(maket.maket_file.path, 'rb'), content_type='application/pdf')
    except:
        maket.uploaded = False
        maket.save()
        return HttpResponse('<script type="text/javascript">window.close();</script>')


def look_up(request, navi):
    if navi == 'orders':
        try:
            lookup = request.POST['look_up']
        except:
            lookup = navi.split('_')[1]
        try:
            orders = Order_imports.objects.filter(Q(order_id__icontains=lookup) | Q(customer__name__icontains=lookup) | \
                                                  Q(manager__manager__icontains=lookup)).order_by('-order_date')
            ord_imp = orders.order_by('-order_date', '-id').first()
            item_import = list(Item_imports.objects.filter(order=ord_imp.id).order_by('code'))
            print_import = ()
            for item in item_import:
                print_import = print_import + tuple(Print_imports.objects.filter(item=item))
            print_import = list(print_import)

            context = {'navi': navi, 'ord_imp': ord_imp, 'item_import': item_import, 'print_import': print_import,
                       'orders': orders, 'active1': 'active', 'look_up': True, 'lookup': lookup}
            context.update(count_errors())
            return render(request, 'orders/index.html', context)
        except:
            return HttpResponseRedirect(reverse('orders:index'))
    elif navi == 'maket_base':
        try:
            lookup = request.POST['look_up']
        except:
            pass
        if lookup == '':
            return HttpResponseRedirect(reverse('maket:maket_base'))

        item = Item_imports.objects.filter(print_name__icontains=lookup)
        ord_s = []
        for itm in item:
            if itm.order not in ord_s:
                ord_s.append(itm.order)
        maket = Makety.objects.filter(Q(order__order_id__icontains=lookup)
                                      | Q(order__customer__name__icontains=lookup)
                                      | Q(order__in=ord_s)
                                      | Q(order__item_imports__name__icontains=lookup)).order_by('-order_date', 'maket_id')

        item_group = Itemgroup_in_Maket.objects.all().order_by('item')
        f_group = {}
        for i in item_group:
            if i.maket not in f_group:
                f_group[i.maket] = []
            if i.checked:
                ig_q = 0
                ig_p = 0
                ig_pp = 0
                itms = Item_imports.objects.filter(
                    Q(order=i.maket.order) & Q(item__print_group=i.item.item.print_group))
                for it in itms:
                    ig_q = ig_q + it.quantity
                    ig_p = ig_p + it.quantity * it.item_price
                    ig_pp = ig_pp + it.quantity * it.print_price
                f_group[i.maket].append([i, ig_q, ig_p, ig_pp])

        f_maket = {}
        for m in maket:
            if m.order not in f_maket:
                f_maket[m.order] = {}
            f_maket[m.order].update({m: f_group.get(m)})

        films = Films.objects.filter(status=False).order_by('-date')
        current_date = datetime.date.today()
        try:
            last_film = films.first().film_id + 1
        except:
            last_film = 1
        if len(f_maket) == 0:
            return HttpResponseRedirect(reverse('maket:maket_base'))
        context = {'navi': navi, 'active5': 'active', 'f_maket': f_maket, 'films': films,
                   'current_date': current_date, 'last_film': last_film, 'look_up': True, 'lookup': lookup}
        context.update(count_errors())
        return render(request, 'maket/maket_base.html', context)

    elif navi == 'films':
        try:
            lookup = request.POST['look_up']
        except:
            pass
        if lookup == '':
            return HttpResponseRedirect(reverse('films:films'))

        item = Item_imports.objects.filter(print_name__icontains=lookup)
        maket = Makety.objects.filter(Q(order__order_id__icontains=lookup) | Q(order__customer__name__icontains=lookup)) \
            .order_by('-order_date', 'maket_id')
        itg_in = Itemgroup_in_Maket.objects.filter(Q(maket__in=maket) | Q(item__in=item))
        flm_s = []
        for itg in itg_in:
            if itg.film not in flm_s and itg.film is not None:
                flm_s.append(itg.film)

        item_group = Itemgroup_in_Maket.objects.filter(film__in=flm_s).order_by('item')
        f_group = {}
        for i in item_group:
            if i.film not in f_group:
                f_group[i.film] = []
            ig_q = 0
            ig_p = 0
            ig_pp = 0
            itms = Item_imports.objects.filter(Q(order=i.maket.order) & Q(item__print_group=i.item.item.print_group))
            for it in itms:
                ig_q = ig_q + it.quantity
                ig_p = ig_p + it.quantity * it.item_price
                ig_pp = ig_pp + it.quantity * it.print_price
                prints = Print_imports.objects.filter(item=it)
                pr = ''
                len_pr = 0
                for prt in prints:
                    if prt.second_pass:
                        sec_pass = '2 пр., '
                    else:

maket/templates/maket/deleteMaketModal.html
<div class="modal fade" id="deleteMaketModal" tabindex="-1" aria-labelledby="deleteMaketModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteMaketModalLabel">Вы удаляете макет</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form action="delete_maket" id="form_delete_maket" method="post">
     {% csrf_token %}
        <input type="hidden" name="object_to_delete" value="" id="object_to_delete" form="form_delete_maket">
      </form>
        <div class="row pe-3">
            <div class="col text-start" id="object_no"></div>
            <div class="col"> от </div>
            <div class="col text-start" id="object_date"></div>
        </div>
            <div class="row ps-3 fw-bolder" id="object_customer"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        <button type="submit" class="btn btn-danger" form="form_delete_maket">Все равно удалить</button>
      </div>
    </div>
  </div>
</div><!-- Modal delete Maket-->

maket/templates/maket/main.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Макеты</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-fixed/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'maket/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'maket/navbar-top-fixed.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

  </head>
  <body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
  <span class="container-fluid">
    <a class="navbar-brand" href="http://10.0.1.17/wcenter/"><i class="bi bi-palette2"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <span class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link {{active1}}" id="1" aria-current="page"  href="{% url 'orders:index' %}">Заказы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{active5}}" id="5" aria-current="page"  href="{% url 'maket:maket_base' %}">Макеты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{active7}}" id="7" aria-current="page"  href="{% url 'films:films' %}">Пленки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{active8}}" id="8" aria-current="page"  href="{% url 'patterns:patterns' %}">Шаблоны</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link {{active2}} dropdown-toggle" id="2" aria-current="page"
               href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Справочники</a>
               <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'dictionarys:goods' %}">Номенклатура</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:customers' %}">Клиенты</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:customer_groups' %}">Группы Клиентов</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:colors' %}">Цвета</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:print_group' %}">Группы печати</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:print_position' %}">Места печати</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:good_groups' %}">Товарная матрица</a></li>
                <li><a class="dropdown-item" href="{% url 'dictionarys:other' %}">Прочие справочники</a></li>
               </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link {{active6}} dropdown-toggle" id="6" href="#"  aria-current="page"
               role="button" data-bs-toggle="dropdown" aria-expanded="false">Файлы
                <span class="badge bg-danger">
                {{total_files_diff}}
                </span></a>
               <ul class="dropdown-menu flex-nowrap">
                <li><a class="dropdown-item" href="{% url 'file_manage:files_orders' %}">
                    Заказы
                    {% if order_files_diff != 0 %}
                    <span class="badge bg-danger">
                    {{order_files_diff}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'file_manage:files_makety' %}">
                    Макеты
                    {% if maket_files_diff != 0 %}
                    <span class="badge bg-danger">
                    {{maket_files_diff}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'file_manage:files_films' %}">
                    Пленки
                    {% if films_files_diff != 0 %}
                    <span class="badge bg-danger">
                    {{films_files_diff}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'file_manage:files_additional' %}">
                    Дополнительные файлы
                    {% if additional_files_diff != 0 %}
                    <span class="badge bg-danger">
                    {{additional_files_diff}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'file_manage:files_patterns' %}">
                    Шаблоны
                    {% if patterns_files_diff != 0 %}
                    <span class="badge bg-danger">
                    {{patterns_files_diff}}
                    </span>
                    {% endif %}
                    </a></li>
          </ul>
          <li class="nav-item dropdown">
            <a class="nav-link {{active4}} dropdown-toggle" id="4" href="#"  aria-current="page"
               role="button" data-bs-toggle="dropdown" aria-expanded="false">Ошибки
                <span class="badge bg-danger">
                {{err_len}}
                </span></a>
               <ul class="dropdown-menu flex-nowrap">
                <li><a class="dropdown-item" href="{% url 'errors:hex_repairs' %}">
                    Заполнение HEX цветов
                    {% if lost_hex_len != 0 %}
                    <span class="badge bg-danger">
                    {{lost_hex_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'errors:customer_repairs' %}">
                    Измененные клиенты
                    {% if changed_customers_len != 0 %}
                    <span class="badge bg-danger">
                    {{changed_customers_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'errors:color_place_repairs' %}">
                    Отсутствие места нанесения и цвета
                    {% if lost_colors_len != 0 %}
                    <span class="badge bg-danger">
                    {{lost_colors_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'errors:deleted_repairs' %}">
                    Ошибки удаления
                    {% if lost_deleted_len != 0 %}
                    <span class="badge bg-danger">
                    {{lost_deleted_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item text-nowrap" href="{% url 'errors:import_repairs' %}">
                    Ошибки импорта
                    {% if lost_imports_len != 0 %}
                    <span class="badge bg-danger">
                    {{lost_imports_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'orders:order_errors' %}">
                    Ошибки импорта заказов
                    {% if order_errors_len != 0 %}
                    <span class="badge bg-danger">
                    {{order_errors_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'errors:print_position_repairs' %}">
                    Отсутствие позиции нанесения
                    {% if lost_position_len != 0 %}
                    <span class="badge bg-danger">
                    {{lost_position_len}}
                    </span>
                    {% endif %}
                    </a></li>
                <li><a class="dropdown-item" href="{% url 'errors:other' %}">Прочие починки</a></li>
               </ul>
          </li>
      </ul>
      {% if active1 == 'active' or active5 == 'active' %}
      <form action="{% url 'errors:badge_file_count' %}" method="post">
      {% csrf_token %}
      <input type="number" hidden value="{{page_obj.number}}" name="page_no">
      <button type="submit" class="btn btn-secondary">Пересчитать связанные файлы</button>
      </form>
      <form action="/maket/look_up_not_finished/{% if active1 == 'active' %}orders{% elif active5 == 'active' %}maket_base{% endif %}"
            id="form_lookup_not_finished" method="post" class="d-flex">
      {% csrf_token %}
           <button class="btn btn-primary {% if look_up %}text-white{% else %}text-white-50{% endif %}" type="submit" >&nbsp;Не закончено&nbsp;</button>
      </form>
      {% endif %}

      {% if active1 == 'active' or active5 == 'active' or active7 == 'active' or active3 == 'active' or active2 == 'active' %}
      <form action="/maket/look_up/{% if active1 == 'active' %}orders{% elif active5 == 'active' %}maket_base{% elif active7 == 'active' %}films{% elif active2 == 'active' %}customers{% endif %}"
            id="form_lookup" method="post" class="d-flex">
      {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search" name="look_up" id="look_up">
        <button class="btn btn-primary" type="submit" >Поиск</button>
      </form>
      {% endif %}
      <div class="d-flex text-white m-1 pt-1"> v3.6.14</div>
    </span>
  </span>
</nav>

<script src="{% static 'maket/maket.js' %}"></script>
<script src="{% static 'maket/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'maket/jquery.min.js' %}"></script>

{% block content %}{% endblock %}

  </body>
</html>