Makety/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maket/', include('maket.urls')),
    path('dicts/', include('dictionarys.urls')),
    path('patterns/', include('patterns.urls')),
    path('errors/', include('errors.urls')),
    path('films/', include('films.urls')),
    path('maket_layout/', include('maket_layout.urls')),
    path('addfiles/', include('addfiles.urls')),
    path('orders/', include('orders.urls')),
    path('file_manage/', include('file_manage.urls')),
    path('salesreport/', include('salesreport.urls')),

]

films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.films, name='films'),
    path('upload_film', views.upload_film, name='upload_film'),
    path('download_film/<int:id>', views.download_film, name='download_film'),
    path('vieworder/<int:id>', views.vieworder, name='vieworder'),
    path('update_to_film/<str:data_to_film>', views.update_to_film, name='update_to_film'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id_str>', views.reload, name='reload'),
    path('orders/import_order', views.import_order, name='import_order'),
    path('orders/delete_order', views.delete_order, name='delete_order'),
    path('orders/upload_order', views.upload_order, name='upload_order'),
    path('download_order/<int:id>', views.download_order, name='download_order'),
    path('order_edit/<int:id>', views.order_edit, name='order_edit'),
    path('orders/order_save', views.order_save, name='order_save'),
    path('orders/order_errors', views.order_errors, name='order_errors'),
]

orders/views.py
import csv
import datetime
import os

from bs4 import BeautifulSoup
from django.core.files.storage import default_storage
from django.http import HttpResponseRedirect, FileResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from maket.models import Item_color, Order_imports, Item_imports, Print_imports, Detail_set, Customer, Manger, Makety, \
     Additional_Files, Customer_types, Customer_all, Customer_groups
from django.db.models import Q
from django.core.paginator import Paginator

from maket.views import count_errors, place_obj_from_place, print_color_check, print_position_and_color_from_print_obj


def index(request):
    navi = 'orders'
    try:
        ord_i = request.POST['ord_id']
        ord_imp = Order_imports.objects.get(pk=int(ord_i))
    except:
        ord_imp = Order_imports.objects.order_by('-order_date', '-id').first()
    try:
        order_id = ord_imp.id
        item_import = list(Item_imports.objects.filter(order=order_id).order_by('code'))
        print_import = ()
        for item in item_import:
            print_import = print_import + tuple(Print_imports.objects.filter(item=item))
        print_import = list(print_import)
    except:
        pass

    try:
        orders = Order_imports.objects.all().order_by('-order_date', '-id')
        f_maket2 = list(orders)
        paginator = Paginator(f_maket2, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        orders = list(page_obj.object_list)

        date_range = []
        for i in range(page_obj.paginator.num_pages):
            page_obj2 = paginator.get_page(i + 1)
            date_tmp = page_obj2.object_list[-1].order_date.strftime('%d.%m.%Y') +  ' - ' + \
                       page_obj2.object_list[0].order_date.strftime('%d.%m.%Y')
            date_range.append([i + 1, date_tmp])
        context = {'navi': navi, 'ord_imp': ord_imp, 'item_import': item_import, 'print_import': print_import,
                   'orders': orders, 'active1': 'active', 'page_obj': page_obj, 'date_range': date_range}
    except:
        context = {'navi': navi}

    context.update(count_errors())
    return render(request, 'orders/index.html', context)


def reload(request, id_str):
    navi = 'orders'
    ord_i = id_str.split('_')[0]
    try:
        ord_imp = Order_imports.objects.get(pk=int(ord_i))
    except:
        ord_imp = Order_imports.objects.order_by('-order_date', '-id').first()
    order_id = ord_imp.id
    item_import = list(Item_imports.objects.filter(order=order_id).order_by('code'))
    print_import = ()
    for item in item_import:
        print_import = print_import + tuple(Print_imports.objects.filter(item=item))
    print_import = list(print_import)
    try:
        orders = Order_imports.objects.order_by('-order_date', '-id').filter(
            Q(order_id__icontains=id_str.split('_')[1]) | Q(customer__name__icontains=id_str.split('_')[1]))
        context = {'lookup': id_str.split('_')[1]}
    except:
        orders = Order_imports.objects.all().order_by('-order_date', '-id')

    f_maket2 = list(orders)
    paginator = Paginator(f_maket2, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    orders = list(page_obj.object_list)

    date_range = []
    for i in range(page_obj.paginator.num_pages):
        page_obj2 = paginator.get_page(i + 1)
        try:
            date_tmp = str(page_obj2.object_list[0])
            date_range.append([i + 1, 'до ' + date_tmp])
        except:
            date_range.append(['нет данных'])
    context.update({'navi': navi, 'ord_imp': ord_imp, 'item_import': item_import, 'print_import': print_import,
                    'orders': orders, 'active1': 'active', 'page_obj': page_obj, 'date_range': date_range})
    context.update(count_errors())
    return render(request, 'orders/index.html', context)


def import_order(request):
    try:
        os.remove('tmp_file')
    except:
        pass
    file = request.FILES['Chosen']
    file_name = default_storage.save('tmp_file', file)
    tmp = open('tmp_file', 'r', encoding="utf-8")
    demo = tmp.read()
    souphtml = BeautifulSoup(demo, "html.parser")
    souptr = souphtml.find_all("tr")
    trstrings = []
    for tr in souptr:
        tmptr = tr.contents
        tmpstrings = []
        for td in tmptr:
            try:
                tmptd = td.contents[0]
                if tmptd != '':
                    tmpstrings.append(tmptd)
            except:
                pass
        if tmpstrings != []:
            trstrings.append(tmpstrings)

    number_tr = len(trstrings)
    order_no = str(trstrings[2][0])
    order_date = trstrings[1][0]
    order_date = datetime.datetime.strptime(order_date, '%d.%m.%Y').date()
    supplier = str(trstrings[4][0])
    customer_name = str(trstrings[6][0])
    customer_inn = str(trstrings[7][0])
    customer_address = str(trstrings[8][0])
    order_quantity = str(trstrings[10][0])
    ord_sum = str(trstrings[12][0])
    order_sum = ord_sum.replace(',', '.')
    our_manager = str(trstrings[13][0])
    #    our_manager_phone = str(trstrings[14][0])
    customer_manager = str(trstrings[15][0])
    customer_manager_phone = str(trstrings[17][0])
    customer_manager_mail = str(trstrings[16][0])
    if customer_manager_mail != '' and customer_manager_mail != '\xa0':
        try:
            imp_manager = Manger.orders.get(manager_mail=customer_manager_mail)
            if imp_manager.manager == customer_manager:
                customer_manager = imp_manager
            else:
                cust_manager = Manger(manager=customer_manager, manager_phone=customer_manager_phone,
                                      manager_mail=customer_manager_mail)
        except:
            cust_manager = Manger(manager=customer_manager, manager_phone=customer_manager_phone,
                                  manager_mail=customer_manager_mail)
    else:
        cust_manager = Manger(manager=customer_manager, manager_phone=customer_manager_phone)
    cust_manager.save()
    try:
        ord_imp = Order_imports.objects.get(order_id=order_no)
        ord_imp.delete()
    except:
        pass
    ord_imp = Order_imports(order_id=order_no, supplier=supplier, customer_name=customer_name,
                            customer_INN=customer_inn, customer_address=customer_address, order_date=order_date,
                            order_quantity=order_quantity, order_sum=order_sum, our_manager=our_manager,
                                manager=cust_manager)
    try:
        if len(customer_inn) >= 10:
            customer = Customer.objects.get(inn=customer_inn)
            ord_imp.customer = customer
        elif len(customer_inn) <= 10:
            customer = Customer.objects.get(name=customer_name)
            ord_imp.customer = customer
            typegroup_in = order_no[slice(13, 15)]
            if customer.customer_type != typegroup_in:
                customer.customer_type = typegroup_in
                customer.save()
    except:
        region = customer_inn[slice(0, 2)]
        typegroup_in = order_no[slice(13, 15)]
        try:
            typegroup = Customer_types.objects.get(code=typegroup_in)
        except:
            typegroup = ''
        try:
            if len(customer_inn) >= 10:
                customer_all = Customer_all.objects.filter(inn=customer_inn).order_by('frigat_id').last()
            else:
                customer_all = Customer_all.objects.filter(customer_name__in=customer_name).order_by('frigat_id').last()
        except:
            customer_all = None
        customer = Customer(name=customer_name, address=customer_address, inn=customer_inn, region=region,
                            customer_type=typegroup, customer_all=customer_all)
        if customer_all:
            customer_all.customer_type = typegroup
            customer_all.save()
            customer.frigat_id = customer_all.frigat_id
        customer.save()
        ord_imp.customer = customer
    ord_imp.save()
    order_body = range(19, number_tr, 1)
    items_list = []
    print_list = []
    prnt_list = {}
    for i in order_body:
        tr_len = len(trstrings[i])
        if trstrings[i][tr_len - 1] == '1sec_endofline' and trstrings[i][3] != '\xa0':
            itm_clr = trstrings[i][2].split('.')
            itm_group = itm_clr[0]
            prt_name = trstrings[i][3]
            try:
                itm_obj = Detail_set.objects.get(item_name=itm_group)
            except:
                pass

            if len(prt_name) >= 16:
                pr_nm = prt_name[0: 12]
            elif 15 > len(prt_name) > 11:
                pr_nm = prt_name[0: 7]
            else:
                pr_nm = prt_name[0: 3]
            if itm_obj.print_group not in prnt_list:
                prnt_list[itm_obj.print_group] = []
            if len(prnt_list[itm_obj.print_group]) == 0:
                prnt_list[itm_obj.print_group].append(prt_name)
            else:
                tmp = False
                for pr in prnt_list[itm_obj.print_group]:
                    if pr.find(pr_nm) == 0:
                        prt_name = pr
                        tmp = True
                if not tmp:
                    prnt_list[itm_obj.print_group].append(prt_name)
                    tmp = False
            itm_clr.pop(0)
            clr = '.'.join(itm_clr)
            num_details = len(itm_clr)
            x = range(num_details)
            item = Item_imports(print_id=trstrings[i][0], code=trstrings[i][2], name=trstrings[i][1],
                                quantity=trstrings[i][4], print_name=prt_name, order=ord_imp,
                                item_group=itm_group, item_color=clr, item=itm_obj)
            for n in x:
                detail = 'detail' + str(n + 1) + '_color'
                detail_hex = 'detail' + str(n + 1) + '_hex'
                setattr(item, detail, itm_clr[n])
                try:

orders/templates/orders/index.html
{% extends 'maket/main.html' %}
{% block title %}Макеты{% endblock %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
{% block content %}
{% include 'orders/reload.html' %}
{% if look_up != True %}
<div class="row fixed-bottom bg-light p-1 mb-0 pb-0 align-items-center" >
<br><br>
    <div class="col-9 text-start">
<div class="pagination" xmlns="http://www.w3.org/1999/html">
    <span class="step-links dropup">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-sm btn-outline-primary">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm btn-outline-primary">предыдущая</a>
        {% endif %}
        <span class="current btn btn-sm btn-outline-secondary">
           {{ page_obj.object_list.19.order_date|date:"d.m.y" }} - {{ page_obj.object_list.0.order_date|date:"d.m.y" }} (страница {{ page_obj.number }}  из {{ page_obj.paginator.num_pages }})
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm btn-outline-primary">следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-sm btn-outline-primary">последняя &raquo;</a>
        {% endif %}
        &nbsp
            <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="_ChooseClient"
                    data-bs-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                Выбрать даты
            </button>
              <ul class="dropdown-menu fw-bold" aria-labelledby="ChooseClient">
                {% for dt_range in date_range %}
              <li><a class="dropdown-item" href="?page={{ dt_range.0 }}"> {{ dt_range.1 }}</a></li>
                {% endfor %}
              </ul>

    </span>
</div><!-- pagination -->
    </div>
    <div class="col text-end">
        <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="bi bi-wind"></i> Импортировать заказ из Фрегата
        </button><!-- Button trigger modal -->
    </div>
</div>
{% endif %}

<!-- Modal delete Order-->
<div class="modal fade" id="deleteOrderModal" tabindex="-1" aria-labelledby="deleteOrderModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteOrderModalLabel">Вы удаляете заказ и все связанные макеты</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form action="{% url 'orders:delete_order' %}" method="post" id="form_delete_order">
      {% csrf_token %}
        <input type="hidden" name="object_to_delete" value="" id="object_to_delete">
      </form>
        <div class="row">
            <div class="col" id="object_no"></div>
            <div class="col" id="object_date"></div>
        </div>
            <div class="row p-3" id="object_customer"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        <button type="submit" class="btn btn-danger" form="form_delete_order">Все равно удалить</button>
      </div>
    </div>
  </div>
</div><!-- Modal delete Order-->


<!-- Modal upload_order -->
<div class="modal fade" id="uploadOrder" tabindex="-1" aria-labelledby="uploadOrderLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="uploadOrderLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'orders:upload_order' %}" method="post" id="upload_order_" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="modal-body m-1">
         <!-- Выбор файла --->
         <label class="custom-file-label" for="ChoseOrder"></label>
         <input type="file" accept=".pdf" class="custom-file-input form-control col-auto border"
                id="ChoseOrder" name="ChoseOrder" form="upload_order_">
          <input type="number" name="upload_id" id="upload_id" form="upload_order_" hidden>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button type="submit" name="submit" class="btn btn-primary" form="upload_order_">Загрузить</button>
      </div>
      </form>
    </div>
  </div>
</div>
<!-- Modal Upload order -->


<!-- Modal import_order -->
<form id="import_order" action="{% url 'orders:import_order' %}" method="post" enctype="multipart/form-data"
      onsubmit="javascript:block_button();">
{% csrf_token %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Выберите файл</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
         <!-- Выбор файла --->
         <label class="custom-file-label" for="ChoseCSV"></label>
         <input type="file" accept=".html" class="custom-file-input col-auto border" id="ChoseCSV" name="Chosen" required>
<!--         <input type="submit" name="submit" value="Upload" /><--->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button type="submit" name="submit" class="btn btn-primary" id="but_imp_modal" >Загрузить</button>
      </div>
    </div>
  </div>
</div>
</form><!-- Modal Import order -->

<div>
<table class="table table-info table-hover" style="font-size:90%;">
    <tbody >
    {% for ord in orders %}
    <tr ondblclick={% if page_obj.number == '' %}"window.location.href='/orders/{{ord.id}}_{{lookup}}'"{% else %}
           "window.location.href='/orders/{{ord.id}}_{{lookup}}?page={{page_obj.number}}'"{% endif %}
           class="align-middle
           {%  if ord.maket_status == 'R' %} text-success{% elif ord.maket_status == 'N' %} text-danger {% endif %}">
        <td class="{% if ord.to_check %}text-danger{% else %}text-success{% endif %}"
            style="font-size: 140%;" onclick="window.open ('/orders/order_edit/{{ord.id}}', '_blank');">
            {% if ord.to_check %}<i class="bi bi-exclamation-square" data-bs-toggle="tooltip"
                    data-bs-title="заказ импортировлся с ошибкой, по клику — переход в редактирование заказа"></i></i>{% else %}
            <i class="bi bi-check-square" data-bs-toggle="tooltip"
                    data-bs-title="импортировано без ошибок"></i>{% endif %}</td>
        <td class="fw-bold" data-bs-toggle="tooltip"
                    data-bs-title="{% if ord.maket_status == 'N' %}макета нет{% elif ord.maket_status == 'P' %}
                    макет сделан частично{% else %}макет готов{% endif %}">{{ord.maket_status}}</td>
        <td>
            <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="tooltip"
                    data-bs-title="посмотреть все связанные файлы: заказ/макет/прочие"
                    onclick="window.open('/addfiles/{{ord.id}}', '_blank');">
                <i class="bi bi-folder2-open">&nbsp;</i><span class="badge text-secondary">
                {{ord.number_orders}} / {{ord.number_makets}} / {{ord.number_additional}}
                </span>
            </button>
        </td>
        <td >
            <button type="button" class="btn btn-sm btn-outline-primary text-nowrap" style="font-size:80%"
                    onclick="upload_order({{ord.id}});" data-bs-toggle="modal" data-bs-target="#uploadOrder">
                <i class="bi bi-upload"></i> на сервер
            </button>
        </form>
        </td>
        <td>
            <button type="button" class="btn btn-sm btn-outline-secondary  text-nowrap" id="but_upl_{{ord.id}}"
                    onclick="window.open('/orders/download_order/{{ord.id}}', '_blank');"
                    style="font-size:80%" {% if not ord.order_upload %}disabled{% endif %}>
                <i class="bi bi-download"></i> открыть
            </button>
        </td>
        <td id="ord_id_{{ord.id}}">{{ord.order_id}}</td>
        <td id="order_date_{{ord.id}}">{{ord.order_date|date:'d.m.Y'}}</td>
{% if 'Сувенир' in ord.supplier %}
        <td> ВВС </td>
{% elif 'Студия' in ord.supplier %}
        <td> ССП </td>
{% else %}
        <td> ВВ </td>
{% endif %}
        <td class="text-wrap" style="max-width:440px" id="cust_nm_{{ord.id}}"> {{ord.customer.name}}</td>
        <td> {{ord.manager.manager}}</td>
        <td class="text-break"> {{ord.manager.manager_mail}}</td>
        <td class="text-end"> {{ord.order_sum}}</td>
        <td class="align-middle">
            <button type="button"  class="btn btn-sm btn-outline-danger text-nowrap" data-bs-toggle="modal"
                    data-bs-target="#deleteOrderModal" onclick="delete_object_modal({{ord.id}});"
                    style="font-size:80%;">
                <i class="bi bi-x-lg"></i> Удалить Заказ</button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div><!-- Table of orders -->
<div>
</div>
<br><br>
<script>
    $(function () {
      $('[data-bs-toggle="tooltip"]').tooltip()
    })
</script>

{% endblock %}

orders/templates/orders/order_edit.html
<!DOCTYPE html>
{% load static %}
{% load extras %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'maket/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'maket/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <title>Заказ {{ord_imp.order_id}} от {{ord_imp.order_date|date:'d.m.Y'}} &nbsp {{ord_imp.customer.name}}</title>
</head>
<body>

<div class="border border-3 border-primary ms-1 p-1 fixed-bottom bg-primary text-white">
<div class="d-flex flex-row lh-1">
    <input type="hidden" name="order_id" value="{{ord_imp.id}}" form="order_save">
    <div class="m-2">ЗАКАЗ {{ord_imp.order_id}}  от {{ord_imp.order_date|date:'d.m.Y'}}</div>
    <div class="m-2">{{ord_imp.customer.name}},</div>
    <div class="align-middle m-2">менеджер</div>
    <div class="align-middle m-2">{{ord_imp.manager.manager}},</div>
    <div class="align-middle m-2">E-mail: {{ord_imp.manager.manager_mail}},</div>
    <div class="align-middle m-2">тел. {{ord_imp.manager.manager_phone}}</div>
    <div class="col text-end">
    <button class="btn btn-sm btn-primary" type="button" onclick="order_repaired({{ord_imp.id}});">
    {% if ord_imp.to_check %}<i class="bi bi-check-lg"></i>Исправить{% else %}
    <i class="bi bi-question-lg"></i>Проверить{% endif %}
    </button></div>
    <button class="btn btn-sm btn-primary" type="submit" form="order_save">
    Cохранить изменения
    </button></div>
</div><!-- Order -->
</div>
<tr class="" >
<table class="table table-hover lh-1 " id="collapse_{{ord_imp.id}}">
    <thead class="sticky-top bg-white">
    <tr class="text-center lh-1 sticky-top">
        <th scope="col" class="col" style="font-size:80%;"> # </th>
        <th scope="col" class="col" style="font-size:80%;"> Арт. </th>
        <th scope="col" class="col-3" style="font-size:80%;"> Наименование </th>
        <th scope="col" class="col-2" style="font-size:80%;"> Нанесение </th>
        <th scope="col" class="col" style="font-size:80%;"> Кол-во </th>
        <th colspan="5" scope="col" class="col" style="font-size:80%;"> Место / Тип / Цветов / 2-й проход </th>
    </tr>
    </thead>
    {% for item in item_import %}
    <form action="{% url 'orders:order_save' %}" method="post" id="order_save">
    {% csrf_token %}
    <tbody class="border-bottom-0">
    <tr class="lh-1" id="row_{{item.print_id}}">
        <td class="col text-center" style="font-size:80%;"> {{item.print_id}} </td>
        <td class="col text-center" style="font-size:80%;"> {{item.code}} </td>
        <td class="col-3" style="font-size:80%;"> {{item.name}}</td>
        <td class="col-2 text-center" style="font-size:80%;"> {{item.print_name}}</td>
        <td class="col text-center" style="font-size:80%;"> {{item.quantity}}</td>
<!--    <td colspan="4">
    <table class="table-sm mb-0"><--->
        <td colspan="4">
            <select class="form-select" aria-label="print_select" style="font-size:80%;" form="order_save"
                    onchange="replace_print_rows(this);" name="{{item.print_id}}"
                    data-id={{item.print_id}} data-id_current={{item.print_id}} id="select_{{item.print_id}}" >
              {% for print_id in print_ids %}
                <option value="{{print_id.0.print_id}}" {% if print_id.0.print_id == item.print_id %}selected{% endif %}
                        id="option_{{item.print_id}}_{{print_id.0.print_id}}">{{print_id.0.print_id}}.&nbsp; {{print_id.0.code}} &nbsp;нанесений: {{print_id.1}} &nbsp; нанесение: {{print_id.0.print_name}} </option>
              {% endfor %}
            </select>
        </td>
    </tr>
    </tbody>
    <tbody class="border-top-0 lh-1 align-top"  id="print_row_{{item.print_id}}" data-id="print_row_{{item.print_id}}">
    {% for prt in print_import %}
    {% if prt.print_id == item.print_id %}
    <tr >
        <td colspan="5" > </td>
        <td class="col text-start" style="font-size:80%;"> {{prt.print_id}}.</td>
        <td class="col text-start" style="font-size:80%;"> {{prt.place}} /</td>
        <td class="col text-center" style="font-size:80%;"> {{prt.type}} /</td>
        <td class="col text-center" style="font-size:80%;"> {{prt.colors}} /</td>
        <td class="col text-center" style="font-size:80%;">
        <input class="form-check-input" type="checkbox" disabled {% if prt.second_pass %}checked{% endif %}>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</form>
</table>
</div><!-- Table border -->
</div><!-- Collapse table -->
</div>
<br><br>



<script src="{% static 'maket/maket.js' %}"></script>
<script src="{% static 'maket/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>

</body>
</html>