Makety/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maket/', include('maket.urls')),
    path('dicts/', include('dictionarys.urls')),
    path('patterns/', include('patterns.urls')),
    path('errors/', include('errors.urls')),
    path('films/', include('films.urls')),
    path('maket_layout/', include('maket_layout.urls')),
    path('addfiles/', include('addfiles.urls')),
    path('orders/', include('orders.urls')),
    path('file_manage/', include('file_manage.urls')),
    path('salesreport/', include('salesreport.urls')),

]

dictionarys/urls.py
from django.urls import path
from . import views

app_name = 'dictionarys'

urlpatterns = [
    path('goods', views.goods, name='goods'),
    path('add_detail', views.add_detail, name='add_detail'),

    path('customers', views.customers, name='customers'),
    path('update_cst', views.update_cst, name='update_cst'),

    path('customer_groups', views.customer_groups, name='customer_groups'),
    path('update_cst_group', views.update_cst_group, name='update_cst_group'),

    path('colors', views.colors, name='colors'),
    path('add_clr', views.add_clr, name='add_clr'),

    path('print_group', views.print_group, name='print_group'),
    path('update_pg', views.update_pg, name='update_pg'),

    path('print_position', views.print_position, name='print_position'),
    path('update_prt_pos/<int:id>', views.update_prt_pos, name='update_prt_pos'),
    path('add_prt_pos', views.add_prt_pos, name='add_prt_pos'),
    path('delete_print_position/<int:id>', views.delete_print_position, name='delete_print_positon'),

    path('matrix', views.good_groups, name='good_groups'),
    path('update_matrix_type/<int:id>', views.update_matrix_type, name='update_matrix_type'),
    path('add_matrix_type', views.add_matrix_type, name='add_matrix_type'),
    path('delete_matrix_type/<int:id>', views.delete_matrix_type, name='delete_matrix_type'),

    path('other', views.other, name='other'),

    path('update_clr_sch/<int:id>', views.update_clr_sch, name='update_clr_sch'),
    path('add_clr_sch', views.add_clr_sch, name='add_clr_sch'),

    path('update_prt_typ/<int:id>', views.update_prt_typ, name='update_prt_typ'),
    path('add_prt_typ', views.add_prt_typ, name='add_prt_typ'),

    path('update_prt_plc/<int:id>', views.update_prt_plc, name='update_prt_plc'),
    path('add_prt_plc', views.add_prt_plc, name='add_prt_plc'),
    path('delete_print_place/<int:id>', views.delete_print_place, name='delete_print_place'),

    path('update_crm_type/<int:id>', views.update_crm_type, name='update_crm_type'),
    path('add_crm_type', views.add_crm_type, name='add_crm_type'),
    path('delete_crm_type/<int:id>', views.delete_crm_type, name='delete_crm_type'),

    path('update_cst_type/<int:id>', views.update_cst_type, name='update_cst_type'),
    path('add_cst_type', views.add_cst_type, name='add_cst_type'),
    path('delete_cst_type/<int:id>', views.delete_cst_type, name='delete_cst_type'),

    path('scale', views.scale, name='scale'),

]

films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.films, name='films'),
    path('upload_film', views.upload_film, name='upload_film'),
    path('download_film/<int:id>', views.download_film, name='download_film'),
    path('vieworder/<int:id>', views.vieworder, name='vieworder'),
    path('update_to_film/<str:data_to_film>', views.update_to_film, name='update_to_film'),

]

dictionarys/views.py
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse
from maket.models import Color_scheme, Print_type, Print_place, Print_position, Item_color, Detail_set, Customer, \
    Print_group, Good_crm_type, Good_matrix_type, Customer_types, Customer_groups, Order_imports
from django.db.models import Q


from Makety.service import count_errors, look_up_cst
from decimal import Decimal


def goods(request):
    navi = 'customers'
    goods = Detail_set.objects.all().order_by('item_name')
    clr_scheme = Color_scheme.objects.all()
    goods_matrix = Good_matrix_type.objects.all()
    goods_crm = Good_crm_type.objects.all()
    color_scheme = []
    for clr in clr_scheme:
        color_scheme.append(clr.scheme_name)
    print_group = []
    prt_group = Print_group.objects.all().order_by('code')
    for prt in prt_group:
        print_group.append(prt.code)

    paginator = Paginator(goods, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'navi': navi, 'page_obj': page_obj, 'active2': 'active', 'color_scheme': color_scheme,
               'print_group': print_group, 'goods_matrix': goods_matrix, 'goods_crm': goods_crm}
    context.update(count_errors())
    return render(request, 'dictionarys/goods.html', context)


def add_detail(request):
    page_no = '?page=' + request.POST['page_no']
    good_id = request.POST['dt_it_id']
    item_code = request.POST['dt_it_art']
    name = request.POST['dt_it_nm']
    cs = request.POST['dt_it_clr']
    eco = request.POST['eco']
    try:
        color_scheme = Color_scheme.objects.get(scheme_name=cs)
    except:
        color_scheme = None
    try:
        matrix_in = request.POST['matrix']
        matrix = Good_matrix_type.objects.get(id=matrix_in)
    except:
        matrix = None
    try:
        crm_in = request.POST['crm']
        crm = Good_crm_type.objects.get(id=crm_in)
    except:
        crm = None
    try:
        pg = request.POST['dt_it_pg']
        print_group = Print_group.objects.get(code=pg)
    except:
        print_group = None

    detail1_name = request.POST['dt1_nm']
    try:
        detail1_place = request.POST['flexCheck_det1']
    except:
        detail1_place = False

    detail2_name = request.POST['dt2_nm']
    if detail2_name != '':
        try:
            detail2_place = request.POST['flexCheck_det2']
        except:
            detail2_place = False
    else:
        detail2_place = False

    detail3_name = request.POST['dt3_nm']
    if detail3_name != '':
        try:
            detail3_place = request.POST['flexCheck_det3']
        except:
            detail3_place = False
    else:
        detail3_place = False

    detail4_name = request.POST['dt4_nm']
    if detail4_name != '':
        try:
            detail4_place = request.POST['flexCheck_det4']
        except:
            detail4_place = False
    else:
        detail4_place = False

    detail5_name = request.POST['dt5_nm']
    if detail5_name != '':
        try:
            detail5_place = request.POST['flexCheck_det5']
        except:
            detail5_place = False
    else:
        detail5_place = False

    detail6_name = request.POST['dt6_nm']
    if detail5_name != '':
        try:
            detail6_place = request.POST['flexCheck_det6']
        except:
            detail6_place = False
    else:
        detail6_place = False
    try:
        det_set = Detail_set.objects.get(id=good_id)
        det_set.item_name = item_code
    except:
        det_set = Detail_set(item_name=item_code)
    det_set.name = name
    det_set.color_scheme = color_scheme
    det_set.print_group = print_group
    det_set.eco = eco
    det_set.crm = crm
    det_set.matrix = matrix
    det_set.detail1_name = detail1_name
    det_set.detail1_place = detail1_place
    det_set.detail2_name = detail2_name
    det_set.detail2_place = detail2_place
    det_set.detail3_name = detail3_name
    det_set.detail3_place = detail3_place
    det_set.detail4_name = detail4_name
    det_set.detail4_place = detail4_place
    det_set.detail5_name = detail5_name
    det_set.detail5_place = detail5_place
    det_set.detail6_name = detail6_name
    det_set.detail6_place = detail6_place
    det_set.save()
    return HttpResponseRedirect(reverse('dictionarys:goods') + page_no)


def customers(request):
    navi = 'customers'
    customers = Customer.objects.all().order_by('customer_all__name', 'name')
    customer_types = Customer_types.objects.all()
    customer_groups = Customer_groups.objects.all().order_by('group_name')
    paginator = Paginator(customers, 25)  # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'navi': navi, 'page_obj': page_obj, 'active2': 'active', 'customer_types': customer_types,
               'customer_groups': customer_groups}
    context.update(count_errors())

    try:
        look_up = request.POST['look_up']
        lookup = request.POST['lookup']
        context.update({'look_up': look_up, 'lookup': lookup})
    except:
        pass

    return render(request, 'dictionarys/customers.html', context)


def update_cst(request):
    page_no = '?page=' + request.POST['page_no']
    cst_id = request.POST['id']
    cst = Customer.objects.get(id=cst_id)
    nm = request.POST['nm']
    gr_id = request.POST['gr_id']
    try:
        gr = request.POST['gr']
    except:
        gr = None
    rg = request.POST['rg']
    in_ = request.POST['in_']
    ad = request.POST['ad']
    try:
        tp = request.POST['tp']
        type = Customer_types.objects.get(id=tp)
        cst.customer_type = type
    except:
        pass
    if gr != '' or gr_id != '':
        try:
            group = Customer_groups.objects.get(id=gr)
            cst.customer_group = group
        except:
            pass
    cst.name = nm
    cst.region = rg
    cst.inn = in_
    cst.address = ad
    cst.save()
    cst.customer_all.customer_group = cst.customer_group
    cst.customer_all.customer_type = cst.customer_type
    cst.customer_all.region = cst.region
    cst.customer_all.save()
    try:
        lookup_str = request.POST['look_up']
        lookup = request.POST['lookup']
        return render(request, 'dictionarys/customers.html', look_up_cst(lookup))
    except:
        return HttpResponseRedirect(reverse('dictionarys:customers') + page_no)


def customer_groups(request):
    navi = 'customer_groups'
    cst_groups = Customer_groups.objects.all().order_by('group_name')
    cst_types = Customer_types.objects.all()

    paginator = Paginator(cst_groups, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'navi': navi, 'active2': 'active', 'page_obj': page_obj, 'cst_types': cst_types}
    context.update(count_errors())
    return render(request, 'dictionarys/customer_groups.html', context)


def update_cst_group(request):
    page_no = '?page=' + request.POST['page_no']
    group_name = request.POST['gr_nm']
    type_id = request.POST['tp']
    gr_tp = Customer_types.objects.get(id=type_id)
    try:
        group_id = request.POST['gr_id']
        group = Customer_groups.objects.get(id=group_id)
        group.group_name = group_name
    except:
        group = Customer_groups(group_name=group_name)
    group.group_type = gr_tp
    group.save()
    return HttpResponseRedirect(reverse('dictionarys:customer_groups') + page_no)


def colors(request):
    navi = 'colors'
    color = Item_color.objects.all().order_by('-color_scheme', 'color_id')
    color_scheme = Color_scheme.objects.all()
    context = {'navi': navi, 'color': color, 'active2': 'active', 'color_scheme': color_scheme}
    context.update(count_errors())
    return render(request, 'dictionarys/colors.html', context)


def add_clr(request):
    color_id = request.POST['clr_id']
    color_name = request.POST['clr_nm']
    color_code = request.POST['dt1_hex']
    pantone = request.POST['dt1_ptn']
    color_scheme = request.POST['ColorSelect_add']
    color_scheme = Color_scheme.objects.get(id=color_scheme)
    try:
        id = request.POST['id_id']
        color = Item_color.objects.get(id=id)
        color.color_id = color_id
        color.color_name = color_name
        color.color_code = color_code
        color.pantone = pantone
        color.color_scheme = color_scheme
    except:
        color = Item_color(color_id=color_id, color_name=color_name, pantone=pantone,
                           color_code=color_code, color_scheme=color_scheme)
    color.save()
    return HttpResponseRedirect(reverse('dictionarys:colors'))


def print_group(request):
    navi = 'print_group'
    print_group = Print_group.objects.all().order_by('code')
    first = print_group.first()
    scale = round(first.item_width / first.item_width_initial * 100, 3)
    context = {'navi': navi, 'active2': 'active', 'print_group': print_group, 'scale': scale}
    context.update(count_errors())
    return render(request, 'dictionarys/print_group.html', context)


def update_pg(request):
    cd = request.POST['pg_cd']
    nm = request.POST['pg_nm']
    op = request.POST['pg_op']
    ly = request.POST['pg_ly']
    width = request.POST['pg_width']
    height = request.POST['pg_height']
    width_initial = request.POST['pg_width_initial']
    height_initial = request.POST['pg_height_initial']
    try:
        pg_id = request.POST['pg_id']
        pg = Print_group.objects.get(id=pg_id)
        pg.code = cd
        pg.name = nm
        pg.options = op
        pg.layout = ly
        pg.item_width = width
        pg.item_height = height
        pg.item_width_initial = width_initial
        pg.item_height_initial = height_initial
    except:
        pg = Print_group(code=cd, name=nm, layout=ly, options=op, item_width=width, item_height=height,

salesreport/views/customer.py
from django.http import FileResponse
from django.shortcuts import render, HttpResponseRedirect, reverse
import datetime
from maket.models import Customer_all, Customer_groups
from django.core.paginator import Paginator
from Makety.service import *
from django.core.files.storage import default_storage


def customer_active(request):
    navi = 'Клиенты'
    customers = Customer_all.objects.filter(date_last__gt=datetime.date(2017, 1, 1), internal=False).order_by('name')
    customer_types = Customer_types.objects.all()
    customer_groups = Customer_groups.objects.all().order_by('group_name')

    context = {'navi': navi, 'page_obj': customers, 'customer_types': customer_types,
               'customer_groups': customer_groups}
    return render(request, 'salesreport/customers.html', context)


def update_cst(request):
    cst_id = request.POST['id']
    cst = Customer_all.objects.get(id=cst_id)
    nm = request.POST['nm']
    gr_id = request.POST['gr_id']
    try:
        gr = request.POST['gr']
    except:
        gr = None
    rg = request.POST['rg']
    in_ = request.POST['in_']
    ad = request.POST['ad']
    try:
        tp = request.POST['tp']
        type = Customer_types.objects.get(id=tp)
        cst.customer_type = type
    except:
        pass
    if gr != '' or gr_id != '':
        try:
            group = Customer_groups.objects.get(id=gr)
            cst.customer_group = group
        except:
            pass
    try:
        request.POST['in']
        cst.internal = True
    except:
        pass
    cst.name = nm
    cst.region = rg
    cst.inn = in_
    cst.address = ad
    cst.save()
    '''
    try:
        lookup_str = request.POST['look_up']
        lookup = request.POST['lookup']
        return render(request, 'salesreport/customers.html', look_up_cst(lookup))
    except:
    '''
    return HttpResponseRedirect(reverse('salesreport:customers_active'))


def import_inn(request):
    customers_no_inn = Customer_all.objects.filter(inn='', internal=False).values_list('frigat_id', flat=True)
    with open('cust_file', newline='', encoding='utf-8') as group_csv:
        for line in enumerate(group_csv, 1):
            row = line[1].rstrip('\r\n').split(';')
            if row[0] in customers_no_inn and row[3] != '':
                inn = row[3]
                if len(inn) == 9 or len(inn) == 11:
                    inn = '0' + str(inn)
                customer = Customer_all.objects.get(frigat_id=row[0])
                customer.inn = inn
                customer.save()
    return HttpResponseRedirect(reverse('salesreport:customers_active'))

def export_cst_types(request):
    customers = Customer_all.objects.filter(customer_type__isnull=False, internal=False)
    customers_int = Customer_all.objects.filter(internal=True)
    date_rep = datetime.date.today().strftime('%d%m%Y')
    export_file_name = 'export_types_' + date_rep + '.csv'

    with open(export_file_name, 'a+', newline='', encoding='utf-8') as export_file:
        for customer in customers:
            string = customer.frigat_id + ';' + customer.customer_type.code + ';' + \
                     str(customer.internal) + ';' + customer.name + ';' + customer.inn + '\n'
            export_file.write(string)
        for customer in customers_int:
            string = customer.frigat_id + ';' + '' + ';' + \
                     str(customer.internal) + ';' + customer.name + ';' + customer.inn + '\n'
            export_file.write(string)
    try:
        return FileResponse(open(export_file_name, 'rb'), content_type='application/force-download')
    except:
        return HttpResponseRedirect(reverse('salesreport:customers_active'))

dictionarys/templates/dictionarys/colors.html
{% extends 'maket/main.html' %}
{% block title %}Справочники{% endblock %}
{% block content %}
<div class="d-flex justify-content-between ms-2 me-3">
      <div><h5>Цвета</h5></div>
<div class="text-end">
    <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal" data-bs-target="#addclrModal">
      Добавить цвет</button>
</div>
</div>
<!-- Modal -->
    <form id="add_clr" action="{% url 'dictionarys:add_clr' %}" method="post">
      {% csrf_token %}
        <div class="modal fade" id="addclrModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="addclrModalLabel">Добавление/Изменение Цвета</h5>
              </div>
              <div class="modal-body">
                 <!--  --->
               <input hidden type="text" class="form-control" id="id_id" name="id_id" >

              <div class="row p-1">
                  <div class="col-4">
                      <input type="text" class="form-control" name="clr_id" placeholder="Цвет" id="clr_id"></div>
                  <div class="col-8">
                      <input type="text" class="form-control" name="clr_nm" placeholder="Название" id="clr_nm"></div>

              </div>
              <div class="row p-1">
                    <div class="col-4">
                        <input type="text" class="form-control" name="dt1_ptn" placeholder="Pantone" id="dt1_ptn"></div>
                    <div class="col-3">
                        <input type="text" class="form-control" name="dt1_hex" placeholder="#HEX" id="dt1_hex"></div>
                    <div class="col-5">
                    <div class="input-group" >
                    <select class="form-select" id="ColorSelect_add" name="ColorSelect_add">
                    {% for clr_sch in color_scheme %}
                         <option id="sch_id_{{ clr_sch.id}}" value="{{ clr_sch.id}}" >{{ clr_sch.scheme_name}}</option>
                    {% endfor %}
                    </select>
                    </div>
                    </div>
              </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                        onclick="javascript:clear_color_modal();">Закрыть</button>
                <button type="submit" class="btn btn-primary">Сохранить</button>
              </div>
            </div>
          </div>
        </div>
    </form>

<table class="table table-sm table-hover">
<thead>
<tr class="table-info" onclick="javascript:colapse_('5');" style="font-size: 80%;">
    <th class="ps-3">ID</th>
    <th >Название</th>
    <th >Pantone С</th>
    <th >#HEX</th>
    <th >Цветовая группа</th>
    <th></th>
</tr>
</thead>
<tbody id="collapse_5">
{% for clr in color %}
<tr style="font-size: 80%;">
    <td id="clrid_{{clr.id}}" class="ps-3">{{clr.color_id}}</td>
    <td id="clrnm_{{clr.id}}">{{clr.color_name}}</td>
    <td id="clrpnt_{{clr.id}}">{{clr.pantone}}</td>
    <td id="clrhex_{{clr.id}}">{{clr.color_code}}</td>
    <td id="ColorSelect2_{{clr.id}}">{{ clr.color_scheme.scheme_name}}</td>
    <input type="hidden" id="option_{{clr.id}}" value="{{ clr.color_scheme.id}}">
    <td class="text-end">
        <button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#addclrModal"
                onclick="javascript:clr_edit({{clr.id}});">Редактировать</button>
    </td>
</tr>
{% endfor %}
</tbody>
</table>


{% endblock %}

dictionarys/templates/dictionarys/customers.html
{% extends 'maket/main.html' %}
{% load static %}
{% block title %}Клиенты{% endblock %}
{% block content %}
{% if look_up != True %}
<div class="row fixed-bottom bg-light p-1 mb-0 pb-0 align-items-center" >
<br><br>
    <div class="col-9 text-start">
<div class="pagination" xmlns="http://www.w3.org/1999/html">
    <span class="step-links dropup">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-sm btn-outline-primary">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm btn-outline-primary">предыдущая</a>
        {% endif %}
        <span class="current btn btn-sm btn-outline-secondary">
           страница {{ page_obj.number }}  из {{ page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm btn-outline-primary">следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-sm btn-outline-primary">последняя &raquo;</a>
        {% endif %}
    </span>
</div><!-- pagination -->
    </div>
    <div class="col text-end">
        {{ page_obj.object_list.0}} - {{ page_obj.object_list.24}}
<!--            <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="_ChooseClient"
                    data-bs-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
            </button>
              <ul class="dropdown-menu fw-bold" aria-labelledby="ChooseClient">
                {% for c_range in cst_range %}
              <li><a class="dropdown-item" href="?page={{ c_range.0 }}"> {{ c_range.1 }}</a></li>
                {% endfor %}
              </ul><--->
    </div>
</div>
{% endif %}

<!--Customer Modal -->
<div class="modal fade" id="custModal" tabindex="-1" aria-labelledby="custModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="custModalLabel">Редактировать Клиента</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'dictionarys:update_cst' %}" method="post" id="form_">
      {% csrf_token %}
      <div class="modal-body">
        <input type="text" name="lookup" value="{{lookup}}" hidden>
        <input type="text" name="look_up" value="{{look_up}}" hidden>
        <input type="number" class="form-control" form="form_" value="{{page_obj.number}}" name="page_no" hidden>
        <div class="row mb-1">
            <div class="col">
                <label for="id">ID Макеты</label>
                <input class="form-control" type="text" id="id" name="id" readonly form="form_"></div>
            <div class="col">
                <label for="gr_id">ID группы клиентов</label>
                <input class="form-control" type="text" id="gr_id" name="gr_id" form="form_" readonly></div>
        </div>
        <div class="row mb-1">
            <div class="col-3">
            <label for="rg">регион</label>
            <input class="form-control" type="text" id="rg" name="rg"></div>
            <div class="col-9">
            <label for="rg">ИНН</label>
            <input class="form-control" type="text" id="in" name="in_"></div>
        </div>
        <label for="nm">название</label>
          <textarea class="form-control mb-1" type="text" id="nm" name="nm"></textarea>
        <div class="row mb-1">
            <label for="gr">группа</label>
            <div class="col">
                <select class="form-select" id="gr" name="gr">
                {% for cst_group in customer_groups %}
                    <option value="{{cst_group.id}}">{{cst_group.group_name}}</option>
                {% endfor %}
                </select>
            </div>
<!--            <div class="col">
            <input class="form-control" type="text" id="gr_o" name="gr_o">
            </div>
        </div>
        <div class="row mb-1"><--->
            <label for="tp">тип</label>
            <div class="col">
                <select class="form-select" id="tp" name="tp" aria-label="select tp" form="form_">
                  {% for cst_type in customer_types %}
                  <option value="{{cst_type.id}}">{{cst_type.type_name}}</option>
                  {% endfor %}
                </select>
            </div>
        <!--    <div class="col">
            <input class="form-control" type="text" id="tp_o" name="tp_o"></div> <--->
        </div>
        <label for="ad">адрес</label>
          <textarea class="form-control" type="text" id="ad" name="ad"></textarea>
      </div>
      </form>
      <div class="modal-footer">
        <button type="button" onclick="clearModalCustomers();" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button type="submit" form="form_" class="btn btn-primary">Сохранить</button>
      </div>
    </div>
  </div>
</div>

<table class="table table-sm table-hover ms-1" style="font-size: 80%;">
<thead>
    <tr  class="table-info">
    <th class="text-nowrap"><strong>Fr #&nbsp;</strong></th>
    <th><strong>Название Клиента</strong></th>
    <th colspan=""><strong>Группа</strong></th>
    <th colspan=""><strong>Тип</strong></th>
    <th><strong>Регион</strong></th>
    <th><strong>ИНН</strong></th>
    <th ><strong>Адрес</strong></th>
    <th class="text-nowrap"><strong>E-mail</strong></th>
    <th ><strong>Последняя продажа</strong></th>
    </tr>
</thead>
<tbody>

{% for cst in page_obj %}
    <tr onclick="fillModalCustomers(this);" id="row_{{cst.id}}" data-bs-toggle="modal" data-bs-target="#custModal" data-id="{{cst.id}}"
        data-name="{{cst.name}}" data-group_old="{{cst.group}}" data-group="{{cst.customer_group.id}}"
        data-type_old="{{cst.type}}" data-type="{{cst.customer_type.id}}" data-region="{{cst.region}}" data-inn="{{cst.inn}}"
        data-address="{{cst.address}}" data-group_id="{{cst.customer_group.id}}" data-fr="{{cst.frigat_id}}">
    <input type="text" hidden value="{{cst.id}}" id="id_{{cst.id}}">
    <td id="fr_{{cst.id}}"><div >{{cst.customer_all.frigat_id}}</div></td>
    <td id="nm_{{cst.id}}" class="fw-bold"><div >{{cst.name}}</div></td>
<!--    <td id="gr_{{cst.id}}">{{cst.group}}</td> <--->
    <td id="gr2_{{cst.id}}" class="text-nowrap">{{cst.customer_group.group_name}}</td>
<!--    <td id="tp_{{cst.id}}">{{cst.type}}</td> <--->
    <td id="tp2_{{cst.id}}" class="text-nowrap">{{cst.customer_type.type_name}}</td>
    <td id="rg_{{cst.id}}">{{cst.region}}</td>
    <td id="in_{{cst.id}}" >{{cst.inn}}</td>
    <td id="addr_{{cst.id}}">{{cst.address}}</td>
    <td id="mail_{{cst.id}}">{{cst.customer_all.mail}}</td>
    <td id="dl_{{cst.id}}">{{cst.customer_all.date_last|date:'d.m.Y'}}</td>
    </tr>
{% endfor %}
</tbody>
</table>
<br><br>
<script src="{% static 'dictionarys/dicts.js' %}"></script>

{% endblock %}