Makety/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maket/', include('maket.urls')),
    path('dicts/', include('dictionarys.urls')),
    path('patterns/', include('patterns.urls')),
    path('errors/', include('errors.urls')),
    path('films/', include('films.urls')),
    path('maket_layout/', include('maket_layout.urls')),
    path('addfiles/', include('addfiles.urls')),
    path('orders/', include('orders.urls')),
    path('file_manage/', include('file_manage.urls')),
    path('salesreport/', include('salesreport.urls')),

]

films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.films, name='films'),
    path('upload_film', views.upload_film, name='upload_film'),
    path('download_film/<int:id>', views.download_film, name='download_film'),
    path('vieworder/<int:id>', views.vieworder, name='vieworder'),
    path('update_to_film/<str:data_to_film>', views.update_to_film, name='update_to_film'),

]

salesreport/urls.py
from django.urls import path
from . import views

app_name = 'salesreport'

urlpatterns = [
    path('', views.index, name='index'),

    path('customers_active', views.customer_active, name='customers_active'),
    path('region_97', views.region_97, name='region_97'),
    path('customers_all', views.customers_all, name='customers_all'),
    path('update_cst', views.update_cst, name='update_cst'),
    path('import_inn', views.import_inn, name='import_inn'),
    path('export_cst_types', views.export_cst_types, name='export_cst_types'),

    path('groups', views.groups, name='groups'),
    path('update_cst_group', views.update_cst_group, name='update_cst_group'),
    path('group_export', views.group_export, name='group_export'),
    path('group_import', views.group_import, name='group_import'),

    path('group_lists', views.group_lists, name='group_lists'),
    path('group_delete', views.group_delete, name='group_delete'),
    path('add_to_group', views.add_to_group, name='add_to_group'),
    path('delete_from_group', views.delete_from_group, name='delete_from_group'),

    path('import_report', views.import_report, name='import_report'),
    path('import_cst', views.import_cst, name='import_cst'),

    path('cst_sinhro_group', views.cst_sinhro_group, name='cst_sinhro_group'),
    path('cst_set_inactive', views.cst_set_inactive, name='cst_set_inactive'),
    path('set_frigat_id', views.set_frigat_id, name='set_frigat_id'),

    path('group_set_inactive', views.group_set_inactive, name='group_set_inactive'),
    path('group_set_dates', views.group_set_dates, name='group_set_dates'),

    path('sales_docs', views.sales_docs, name='sales_docs'),
    path('sales_docs_recheck', views.sales_docs_recheck, name='sales_docs_recheck'),
    path('unsinhronized', views.cst_unsinhronized, name='cst_unsinhronized'),
    path('no_inn', views.cst_no_inn, name='cst_no_inn'),

    path('management', views.management, name='management'),
    path('report_periods', views.report_periods, name='report_periods'),
    path('sales_set_periods', views.sales_set_periods, name='sales_set_periods'),
    path('lost_goods', views.lost_goods, name='lost_goods'),

    path('customer_period_sales', views.customer_period_sales, name='customer_period_sales'),
    path('goods_period_sales', views.goods_period_sales, name='goods_period_sales'),

    path('admin', views.admin, name='admin'),
    path('transaction_delete', views.transaction_delete, name='transaction_delete'),
    path('customer_all_delete', views.customer_all_delete, name='customer_all_delete'),

    path('report_customer_period', views.report_customer_period, name='report_customer_period'),
    path('report_customer_migrations', views.report_customer_migrations, name='report_customer_migrations'),
    path('report_customer_geography', views.report_customer_geography, name='report_customer_geography'),

    path('report_goods_group', views.report_goods_group, name='report_goods_group'),
    path('report_goods_type', views.report_goods_type, name='report_goods_type'),

    path('client_transactions/<int:client_id>/<int:period_id>', views.client_transactions, name='client_transactions'),
    path('detail/<int:salesdoc_id>', views.detail, name='detail'),

]

salesreport/views.py
import datetime
from datetime import date
import os


from django.shortcuts import render, HttpResponseRedirect, reverse
from maket.models import Customer_all, Customer, Customer_groups, Customer_types, Detail_set, Item_color
from .models import Sales_doc_imports, Sales_docs
from django.core.paginator import Paginator
from django.core.files.storage import default_storage
from django.db.models import Q, F


def customer_import_compare(row, customer):
    return customer.name == row[1] and \
           customer.form == row[2] and \
           customer.inn == row[3] and \
           customer.address == row[5] and \
           customer.phone == row[6] and \
           customer.mail == row[7] and \
           customer.comment == row[8] and \
           customer.all_phones == row[13] and \
           customer.all_mails == row[12]


def customer_check_row(row):
    result = (len(row) == 14)
    empty = True
    for i in range(2, len(row)):
        empty = empty and (row[i] == '' or row[i] == '0')
    return result and not empty


def customer_type_chose(type, region):
    if 'Конечник' in type and (region == '77' or region == '50'):
        type_obj = Customer_types.objects.get(type_name='Конечник Москва')
    elif 'Конечник' in type and region != '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Конечник Регион')
    elif 'рекламщик' in type and region == '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Рекламщик Москва')
    elif 'рекламщик' in type and region != '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Рекламщик Регион')
    elif 'Агентство' in type and region == '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Агентство Москва')
    elif 'Агентство' in type and region != '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Агентство Регион')
    elif 'Дилер' in type and region == '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Дилер Москва')
    elif 'Дилер' in type and region != '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Дилер Регион')
    elif 'точка' in type and region != '77' and region != '50':
        type_obj = Customer_types.objects.get(type_name='Розничная Точка')
    else:
        type_obj = ''
    return type_obj


def index(request):
    navi = 'Главная'
    try:
        date_last = max(Sales_doc_imports.objects.values_list('import_date', flat=True))
    except:
        date_last = '2000-01-01'
    try:
        date_last_cst = max(Customer_all.objects.values_list('date_import', flat=True))
    except:
        date_last_cst = '2010-01-01'
    customers_all_quantity = Customer_all.objects.all().count()
    customers_active_quantity = Customer.objects.filter(active=True, internal=False).count()
    customers_quantity = Customer.objects.all().count()

    groups_active_quantity = Customer_groups.objects.filter(active=True).count()
    groups_quantity = Customer_groups.objects.all().count()

    clients_active_quantity = Customer.objects.filter(active=True, internal=False, customer_group__isnull=True).count() + \
                              Customer_groups.objects.filter(active=True).count()
    clients_quantity = Customer.objects.filter(customer_group__isnull=True).count() + \
                       Customer_groups.objects.all().count()

    sales_doc_quantity = Sales_docs.objects.all().count()
    transactions_quantity = Sales_doc_imports.objects.all().count()
    no_doc = Sales_doc_imports.objects.filter(sales_doc__isnull=True).count()
    no_cust = Sales_docs.objects.filter(customer__isnull=True).count()
    no_good = Sales_doc_imports.objects.filter(detail_set__isnull=True).count()
    sinhronized = Customer.objects.filter(Q(customer_all__isnull=False) &
                                          Q(group=F('customer_all__group')) &
                                          Q(type=F('customer_all__type')) &
                                          (Q(customer_group=F('customer_all__customer_group')) |
                                          Q(customer_group__isnull=True) & Q(customer_all__customer_group__isnull=True)) &
                                          (Q(customer_type=F('customer_all__customer_type')) |
                                          Q(customer_type__isnull=True) & Q(customer_all__customer_type__isnull=True)) &
                                          Q(inn=F('customer_all__inn')) &
                                          Q(name__endswith=F('customer_all__name'))
                                          ).count()
    context = {'navi': navi, 'date_last_cst': date_last_cst, 'customers_quantity': customers_quantity,
               'customers_active_quantity': customers_active_quantity, 'sinhronized': sinhronized,
               'date_last': date_last, 'sales_doc_quantity': sales_doc_quantity, 'customers_all_quantity': customers_all_quantity,
               'transactions_quantity': transactions_quantity, 'no_doc': no_doc, 'no_cust': no_cust, 'no_good': no_good,
               'groups_quantity': groups_quantity, 'groups_active_quantity': groups_active_quantity,
               'clients_quantity': clients_quantity, 'clients_active_quantity': clients_active_quantity}
    return render(request, 'salesreport/index.html', context)


def import_report(request):
    report_file = request.FILES['importReport']
    start_date = datetime.datetime.strptime(request.POST['start_date'], '%Y-%m-%d').date()
    Sales_doc_imports.objects.filter(sales_doc_date__gte=start_date).delete()
    Sales_docs.objects.filter(sales_doc_date__gte=start_date).delete()
    try:
        Sales_docs.objects.filter(sales_doc_date__gte=start_date).delete()
    except:
        pass
    try:
        os.remove('report_file')
    except:
        pass
    file_name = default_storage.save('report_file', report_file)

    with open(file_name, newline='', encoding='utf-8') as cust_csv:
        records_list = []
        customer_list = []
        for line in enumerate(cust_csv, 1):
            row = line[1].rstrip('\r\n').split(';')
            sales_doc_date = datetime.datetime.strptime(row[13], '%d.%m.%Y').strftime("%Y-%m-%d")
            sales_doc_date = datetime.datetime.strptime(sales_doc_date, '%Y-%m-%d').date()
            if sales_doc_date < start_date:
                continue
            import_date = date.today()
            code_imp = row[0]
            code_list = code_imp.split('.')
            code = code_list[0]
            code_list.pop(0)
            if len(code_list) >= 1 and len(code_list[0]) > 1:
                main_color = code_list[0]
                color_code = '.'.join(code_list)
            elif len(code_list) > 1 and len(code_list[0]) == 1:
                main_color = code_list[1]
                color_code = '.'.join(code_list)
            elif len(code_list) == 1 and len(code_list[0]) == 1:
                main_color = None
                color_code = code_list[1]
            else:
                main_color = None
                color_code = None
            try:
                detail_set = Detail_set.objects.get(item_name=code)
            except:
                detail_set = None
            try:
                item_color = Item_color.objects.get(color_id=main_color, color_scheme=detail_set.color_scheme)
            except:
                item_color = None
            series_id = row[1]
            good_id = row[2]
            good_group_id = row[3]
            good_group = row[4]
            good_title = row[5]
            good_name = row[6]
            code_1 = row[9]
            quantity = float(row[10].replace(',', '.'))
            sales_doc_name = row[11]
            sales_doc_no = row[12]
            buy_without_vat = float(row[14].replace(',', '.'))
            buy_with_vat = float(row[15].replace(',', '.'))
            sales_quantity = float(row[17].replace(',', '.'))
            sale_without_vat = float(row[16].replace(',', '.'))
            sale_with_vat = float(row[18].replace(',', '.'))
            sale_price_vat = float(row[19].replace(',', '.'))
            customer_name = row[21]
            customer_frigat_id = row[20]
            try:
                customer_all = Customer_all.objects.get(frigat_id=customer_frigat_id)
            except:
                pass
            try:
                customer = Customer.objects.get(frigat_id=customer_frigat_id)
            except:
                customer = Customer(frigat_id=customer_frigat_id,
                                    date_first=sales_doc_date,
                                    name=(customer_all.form + ' ' + customer_all.name), address=customer_all.address,
                                    inn=customer_all.inn, region=customer_all.region, type=customer_all.type,
                                    group=customer_all.group, customer_type=customer_all.customer_type,
                                    customer_group=customer_all.customer_group, customer_all=customer_all)
            if customer.date_first == datetime.datetime.strptime('2000-01-01', '%Y-%m-%d').date() \
                    or sales_doc_date < customer.date_first:
                customer.date_first = sales_doc_date
            if customer.date_last == datetime.datetime.strptime('2100-01-01', '%Y-%m-%d').date() \
                    or sales_doc_date > datetime.datetime.strptime(str(customer.date_last), '%Y-%m-%d').date():
                customer.date_last = sales_doc_date
            report_record = Sales_doc_imports(import_date=import_date, code=code, detail_set=detail_set,
                                              color_code=color_code, main_color=main_color, item_color=item_color,
                                              series_id=series_id, good_id=good_id, good_group_id=good_group_id,

salesreport/views/admin.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from maket.models import Customer_all, Customer, Customer_groups, Customer_types, Detail_set, Item_color, Order_imports
from salesreport.models import Sales_doc_imports, Sales_docs

def admin(request):
    navi = 'Admin'
    context = {'navi': navi}
    return render(request, 'salesreport/admin.html', context)


def transaction_delete(request):
    Sales_docs.objects.all().delete()
    Sales_doc_imports.objects.all().delete()
    return HttpResponseRedirect(reverse('salesreport:admin'))

def customer_all_delete(request):
    Customer_all.objects.all().delete()
    '''
    customers_id = set(Order_imports.objects.all().values_list('customer', flat=True))
    Customer.objects.exclude(id__in=customers_id).delete()
    fr_id = [''] * Customer.objects.all().count()
    customers = Customer.objects.all()
    for customer in customers:
        customer.frigat_id = ''
    Customer.objects.bulk_update(customers, ['frigat_id'])
    '''
    return HttpResponseRedirect(reverse('salesreport:admin'))

salesreport/views/customer_all.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from maket.models import Customer_all, Customer, Customer_groups, Customer_types, Detail_set, Item_color
from django.core.paginator import Paginator


def customers_all(request):
    navi = 'Все Клиенты'
    customers = Customer_all.objects.all().order_by('name')
    paginator = Paginator(customers, 50)  # Show 50 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'navi': navi, 'page_obj': page_obj}
    return render(request, 'salesreport/customers_all.html', context)

salesreport/views/exra_reports.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from maket.models import Customer_all, Customer_groups
from salesreport.models import ReportPeriod, Sales_docs, Sales_doc_imports


def client_transactions(request, client_id, period_id):
        period = ReportPeriod.objects.get(id=period_id)
        customer = Customer_all.objects.get(id=client_id)
        group = customer.customer_group
        if not group:
            transactions = Sales_docs.objects.filter(customer=customer, sales_doc_date__gte=period.date_begin,
                                                     sales_doc_date__lte=period.date_end).order_by('sales_doc_date')
            name = customer.name.replace('"', '')
        else:
            transactions = Sales_docs.objects.filter(customer__customer_group=group,
                                                     sales_doc_date__gte=period.date_begin,
                                                     sales_doc_date__lte=period.date_end).order_by('sales_doc_date')
            name = group.group_name

        context = {'transactions': transactions, 'name': name, 'period': period}
        return render(request, 'salesreport/reports/client_transactions.html', context)


def detail(request, salesdoc_id):
    operations = Sales_doc_imports.objects.filter(sales_doc__id=salesdoc_id)
    context = {'operations': operations}
    return render(request, 'salesreport/reports/detail.html', context)

salesreport/templates/salesreport/admin.html
{% extends 'salesreport/main_salesrep.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div class="text-end m-3 text-primary">анализ продаж V 1.1.1</div>
<!-- Customers-->

<button type="button" onclick="window.open('transaction_delete', '_self');" class="btn btn-primary m-3">
    Удалить транзакции
</button>
<button type="button" onclick="window.open('customer_all_delete', '_self');" class="btn btn-primary m-3">
    Удалить базу клиентов и связи с фрегатом
</button>



{% endblock %}

salesreport/templates/salesreport/customer_groups.html
{% extends 'salesreport/main_salesrep.html' %}
{% load static %}
{% block title %}Группы клиентов{% endblock %}
{% block content %}

    <table class="table table-hover ms-3 me-3" style="font-size: 80%;">
        <thead class="sticky-top bg-light" >
        <tr  >
        <th colspan="8">
    <div class="row justify-content-end">
        <div class="col-auto justify-content-end m-2">
            <form action="{% url 'salesreport:group_export' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-outline-secondary">
                    Экспорт Групп Клиентов
                </button>
            </form>
        </div>
        <div class="col-auto justify-content-end m-2">
            <button type="button" class="btn btn-sm btn-outline-primary" data-bs-target="#importGroupModal"
                    data-bs-toggle="modal">
                Импорт Групп Клиентов
            </button>
        </div>
        <div class="col-auto justify-content-end m-2">
            <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#groupModal">
                Добавить Группу Клиентов
            </button>
        </div>
        <div class="col-auto justify-content-end">
            <div class="form-check form-switch mt-3 me-3">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchActive">
                <label class="form-check-label fw-normal" for="flexSwitchActive" style="font-size: 90%;">Только
                    активные</label>
            </div>
        </div>
    </div>
</th>
        </tr>
        <tr class="table-light">
            <th>
                Группа Клиентов&nbsp;(всего&nbsp;{{ group_quan }})
            </th>
            <th>Код</th>
            <th>Тип Группы</th>
            <th>Скидка</th>
            <th>Первая продажа</th>
            <th>Последняя продажа</th>
            <th>Кол-во контрагентов</th>
            <th></th>
        </tr>
        </thead>
        {% for cst_gr in page_obj %}
            <tr {% if not cst_gr.0.active %}class="text-danger"{% endif %}>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.0.group_name }}</td>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.0.group_type.code }}</td>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.0.group_type.type_name }}</td>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.0.group_type.group_discount }}&nbsp;%
                </td>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.0.date_first|date:'d.m.Y' }}</td>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.0.date_last|date:'d.m.Y' }}</td>
                <td data-bs-target="#groupModal" data-bs-toggle="modal" data-id="{{ cst_gr.0.id }}"
                    data-name="{{ cst_gr.0.group_name }}"
                    data-type="{{ cst_gr.0.group_type.id }}"
                    onclick="fillModalCustomerGroups(this);">{{ cst_gr.1 }}</td>
                <td style="display: flex; z-index: 50;" class="text-end">
                    <form action="{% url 'salesreport:group_lists' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="group_id" value="{{ cst_gr.0.id }}">
                        <button type="submit" class="btn btn-sm btn-outline-primary me-1"><i class="bi bi-list-task"
                                                                                             style="z-index: 100"></i>&nbsp;Состав&nbsp;группы
                        </button>
                    </form>
                    <form action="{% url 'salesreport:group_delete' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="group_id" value="{{ cst_gr.0.id }}">
                        <button type="submit" class="btn btn-sm btn-outline-danger ms-1"
                                {% if cst_gr.1 != 0 %}disabled{% endif %}><i class="bi bi-x-lg"></i>&nbsp;Удалить
                            группу
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        <tbody>
        </tbody>
    </table>

    <!-- Modal import cst group -->
    <div class="modal fade" id="importGroupModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="importGroupModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="importGroupModalLabel">Импорт групп</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'salesreport:group_import' %}" method="post" id="group_import"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label class="custom-file-label" for="importGroup"></label>
                        <input type="file" accept=".csv" class="custom-file-input col-auto border" id="importGroup"
                               name="importGroup" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Записать</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



    <!-- Modal upd cst group -->
    <div class="modal fade" id="groupModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="groupModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="groupModalLabel">Редактировать группу</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="update_cst_group" method="post" id="group_update">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class=""><input type="number" name="gr_id" class="form-control" readonly id="id" hidden>
                        </div>
                        <div class="row">
                            <div class="col-7"><input type="text" name="gr_nm" class="form-control" id="nm"></div>
                            <div class="col-5">
                                <select class="form-select" aria-label="Default select example" name="tp" id="tp">
                                    {% for cst_type in cst_types %}
                                        <option value="{{ cst_type.id }}">{{ cst_type.type_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                                onclick="clearModalCustomerGroups();">Закрыть
                        </button>
                        <button type="submit" class="btn btn-primary">Записать</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'salesreport/dicts.js' %}"></script>

{% endblock %}

salesreport/templates/salesreport/main_salesrep.html
<!doctype html>
{% load static %}
<html lang="en">
<title>Анализ продаж</title>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<!-- Bootstrap core CSS -->
<link href="{% static 'maket/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>

<body>
<div class="fixed-top" style="max-width: 100mm;">
<div class="p-2">
<button class="btn btn-outline-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions2" aria-controls="offcanvasWithBothOptions2">
    <i class="fas fa-bars"></i><strong>&nbsp;&nbsp;{{navi}}</strong></button>
</div>
</div>
<div class="offcanvas offcanvas-start" data-bs-scroll="true"
     tabindex="-1" id="offcanvasWithBothOptions2" aria-labelledby="offcanvasWithBothOptions2Label" style="width:60mm;">
<div class="offcanvas-header">
    <strong>{{navi}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body" >
    <p><a href="{% url 'salesreport:index' %}">Главная</a></p>
    <p><a href="{% url 'salesreport:customers_active' %}">Клиенты активные</a></p>
    <p><a href="{% url 'salesreport:customers_all' %}">Клиенты все</a></p>
    <p><a href="{% url 'salesreport:groups' %}">Группы</a></p>
    <p><a href="{% url 'salesreport:group_lists' %}">Списки групп</a></p>
    <p><a href="{% url 'salesreport:management' %}">Управление</a></p>
    <p><a href="{% url 'salesreport:admin' %}">Admin</a></p>
</div>
</div>

<!-- MDB -->
<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"></script><--->
<script src="{% static 'salesreport/salesreport.js' %}"></script>
<script src="{% static 'maket/maket.js' %}"></script>
<script src="{% static 'maket/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'maket/jquery.min.js' %}"></script>

{% block content %}{% endblock %}

</body>
</html>